### ISSUE TITLE
Get key

### ISSUE THREAD

**Issue by Pato2222** [Yopapa699/Key-System#1]
The get key button doesn’t do anything

**Comment by Yopapa699** [comment]
It should copy you a discord invite link

**Comment by Pato2222** [comment]
It didn’t

**Comment by Yopapa699** [comment]
did u check your clipboard?

**Comment by Pato2222** [comment]
Yep

**Comment by Yopapa699** [comment]
Hm I'll take a look at the code later but here's the discord: https://discord.gg/chadhub

**Comment by Pato2222** [comment]
Thx, I’m in iPad btw, maybe thaTs the issue

**Comment by Yopapa699** [comment]
nah prob my hub issue and np

**Comment by Yopapa699** [comment]
fixing
